version: '3'
services:
    server:
        build:
            dockerfile: ./Dockerfile
            context: ./api
        ports:
            - "8088:8088"
    client:
        build:
            dockerfile: ./Dockerfile
            context: ./client
        ports:
            - "3000:3000"